language: android
jdk: oraclejdk8

before_script:
    - export ANDROID_HOME=$HOME/.android
    - mkdir -p $HOME/.android
    - cp -r extra/licenses $ANDROID_HOME/licenses
    - chmod +x gradlew

script:
    - ./gradlew clean test

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    # - platform-tools
    # - tools

    # The BuildTools version used by your project
    - build-tools-25.0.2

    # The SDK version used to compile your project
    - android-25

    # Additional components


    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
